@echo off
echo Resetting any previous stages...
git reset
echo Initializing Git...
git init
echo Configuring remote...
git remote remove origin
git remote add origin git@github.com:Sakthiveldeveloper/portfolio_new_2026.git
echo Adding files (should be much faster now that node_modules is ignored)...
git add .
echo Committing...
git commit -m "Initial commit"
echo Renaming branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
